name: arq-simul
version: 0.5.1
summary: A didactic simulator for different ARQ algorithms

description: |
  This is a simple discrete time event simulator that shows the
  behavior of the main ARQ algorithms. It is built with didactic objectives to
  be used in introductory Computer Networks subjects.

confinement: strict
base: core22
license: GPL-3.0
grade: stable

parts:
  rust-deps:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
  arq-simul:
    plugin: rust
    after: [rust-deps]
    source: .

apps:
  arq-simul:
    command: bin/arq-simul
